---

lowercaseOutputName: true

rules:

#############################
### Kafka Network Metrics ###
#############################

# Request Metrics Histogram
- pattern: kafka\.network<type=(\w+), name=(\w+), request=(\w+)><>([\d]{2,3})thPercentile
  name: kafka_network_$1_$2_$3
  labels:
    metric: quantile|0.$4
    quantile: 0.$4
  type: GAUGE

# Request Metrics Count
- pattern: kafka\.network<type=(\w+), name=(\w+), request=(\w+)><>(Count)
  name: kafka_network_$1_$2_$3_total
  type: COUNTER

# Request Metrics Gauges
- pattern: kafka\.network<type=(\w+), name=(\w+), request=(\w+)><>(Max|Min|Mean|StdDev|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate)
  name: kafka_network_$1_$2_$3
  type: GAUGE
  labels:
    metric: "$4"

############################
### Kafka Server Metrics ###
############################

# Request Handler Pool
- pattern: kafka.server<type=(KafkaRequestHandlerPool), name=(\w+)><>Count
  name: kafka_server_$1_$2_total
  type: COUNTER

- pattern: kafka.server<type=(KafkaRequestHandlerPool), name=(\w+)><>(MeanRate|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate)
  name: kafka_server_$1_$2
  type: GAUGE
  labels:
    metric: $3

# Replica Manager
- pattern: kafka.server<type=(ReplicaManager), name=(\w+)><>Count
  name: kafka_server_$1_$2_total
  type: COUNTER

- pattern: kafka.server<type=(ReplicaManager), name=(\w+)><>Value
  name: kafka_server_$1_$2
  type: GAUGE

- pattern: kafka.server<type=(ReplicaManager), name=(\w+)><>(MeanRate|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate)
  name: kafka_server_$1_$2
  type: GAUGE
  labels:
    metric: $3

# Replica Fetcher Manager
- pattern: kafka.server<type=(ReplicaFetcherManager), name=(\w+), clientId=(\w+)><>Value
  name: kafka_server_$1_$2
  type: GAUGE
  labels:
    clientid: "$3"

# Replica Alter Log Dirs Manager
- pattern: kafka.server<type=(ReplicaAlterLogDirsManager), name=(\w+), clientId=(\w+)><>Value
  name: kafka_server_$1_$2
  type: GAUGE
  labels:
    clientid: "$3"

# Fetch Session Cache
- pattern: kafka.server<type=(FetchSessionCache), name=(\w+)><>Count
  name: kafka_server_$1_$2_total
  type: COUNTER

- pattern: kafka.server<type=(FetchSessionCache), name=(\w+)><>Value
  name: kafka_server_$1_$2
  type: GAUGE

- pattern: kafka.server<type=(FetchSessionCache), name=(\w+)><>(MeanRate|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate)
  name: kafka_server_$1_$2
  type: GAUGE
  labels:
    metric: $3

# Session Expire Listener
- pattern: kafka.server<type=(SessionExpireListener), name=(\w+)><>Count
  name: kafka_server_$1_$2_total
  type: COUNTER

- pattern: kafka.server<type=(SessionExpireListener), name=(\w+)><>(MeanRate|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate)
  name: kafka_server_$1_$2
  type: GAUGE
  labels:
    metric: $3

# ZooKeeper Client Metrics
- pattern: kafka.server<type=(ZooKeeperClientMetrics), name=(\w+)><>Count
  name: kafka_server_$1_$2_total
  type: COUNTER

- pattern: kafka.server<type=(ZooKeeperClientMetrics), name=(\w+)><>([\d]{2,3})thPercentile
  name: kafka_network_$1_$2
  labels:
    metric: quantile|0.$3
    quantile: 0.$3
  type: GAUGE

- pattern: kafka.server<type=(ZooKeeperClientMetrics), name=(\w+)><>(Max|Min|Mean|StdDev|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate)
  name: kafka_network_$1_$2
  type: GAUGE
  labels:
    metric: "$3"

# Kafka Server Metrics
- pattern: kafka.server<type=(KafkaServer), name=([\w-]+)><>Value
  name: kafka_server_$1_$2
  type: GAUGE

# Delayed Operation Purgatory Metrics
- pattern: kafka.server<type=(DelayedOperationPurgatory), name=(\w+), delayedOperation=(\w+)><>Value
  name: kafka_server_$1_$2
  labels:
    delayedoperation: "$3"
  type: GAUGE

# Broker Topic Metrics
- pattern: kafka.server<type=(BrokerTopicMetrics), name=(\w+), topic=(.+)><>(MeanRate|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate)
  name: kafka_server_$1_$2
  labels:
    topic: "$3"
    metric: "$4"
  type: GAUGE

- pattern: kafka.server<type=(BrokerTopicMetrics), name=(\w+), topic=(.+)><>Count
  name: kafka_server_$1_$2_total
  labels:
    topic: "$3"
  type: COUNTER

- pattern: kafka.server<type=(BrokerTopicMetrics), name=(\w+)><>(MeanRate|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate)
  name: kafka_server_$1_$2
  labels:
    metric: "$3"
  type: GAUGE

- pattern: kafka.server<type=(BrokerTopicMetrics), name=(\w+)><>Count
  name: kafka_server_$1_$2_total
  type: COUNTER


############################
# Kafka Controller Metrics #
############################

# Controller Stats Metrics
- pattern: kafka\.controller<type=(ControllerStats), name=(\w+)><>([\d]{2,3})thPercentile
  name: kafka_controller_$1_$2
  labels:
    metric: quantile|0.$3
    quantile: 0.$3
  type: GAUGE

- pattern: kafka\.controller<type=(ControllerStats), name=(\w+)><>(Max|Min|Mean|StdDev|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate)
  name: kafka_controller_$1_$2
  labels:
    metric: $3
  type: GAUGE

- pattern: kafka\.controller<type=(ControllerStats), name=(\w+)><>Count
  name: kafka_controller_$1_$2_total
  type: COUNTER

# Kafka Controller Metrics
- pattern: kafka\.controller<type=(KafkaController), name=(\w+)><>Value
  name: kafka_controller_$1_$2
  type: GAUGE

# Controller Channel Manager Metrics
- pattern: kafka\.controller<type=(ControllerChannelManager), name=(\w+)><>Value
  name: kafka_controller_$1_$2
  type: GAUGE

- pattern: kafka\.controller<type=(ControllerChannelManager), name=([\w-]+), broker-id=(\d+)><>Value
  name: kafka_controller_$1_$2
  labels:
    broker_id: $3
  type: GAUGE


#######################
# Kafka Utils Metrics #
#######################

# Throttler Metrics
- pattern: kafka\.utils<type=(Throttler), name=([\w-]+)><>Count
  name: kafka_utils_$1_$2_total
  type: COUNTER

- pattern: kafka\.utils<type=(Throttler), name=([\w-]+)><>(MeanRate|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate)
  name: kafka_utils_$1_$2
  labels:
    metric: $3
  type: GAUGE


#########################
# Kafka Cluster Metrics #
#########################

# Partition Metrics
- pattern: kafka\.cluster<type=(Partition), name=(\w+), topic=(.+), partition=(\d+)><>Value
  name: kafka_cluster_$1_$2
  labels:
    topic: $3
    partition: $4

#####################
# Kafka Log Metrics #
#####################
# Log Metrics
- pattern: kafka\.log<type=(\w+), name=([\w-]+)><>Value
  name: kafka_log_$1_$2

- pattern: kafka\.log<type=(\w+), name=([\w-]+), logDirectory=(.+)><>Value
  name: kafka_log_$1_$2
  labels:
    logdirectory: $3

#####################
# MATCH ALL RULESET #
#####################

#- pattern: kafka.server<type=(.+), name=(.+)><>([\d]?\w+)
#  name: kafka_server_$1_$2_$3

#- pattern: kafka.controller<type=(.+), name=(.+)><>([\d]?\w+)
#  name: kafka_controller_$1_$2_$3

#- pattern: kafka.cluster<type=(.+), name=(.+)><>([\d]?\w+)
#  name: kafka_cluster_$1_$2_$3

#- pattern: kafka.utils<type=(.+), name=(.+)><>([\d]?\w+)
#  name: kafka_utils_$1_$2_$3

#- pattern: kafka.server<type=(ReplicaManager), name=(.+)><>([\d]?\w+)
#  name: kafka_server_$1_$2_$3

#####################

# THESE ONES ARE GOOD
#
#- pattern: kafka.cluster<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>([\d]?\w+)
#  name: kafka_cluster_$1_$2_$7
#  labels:
#    "$3": "$4"
#    "$5": "$6"

#- pattern: kafka.network<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>([\d]?\w+)
#  name: kafka_network_$1_$1_$7
#  labels:
#    "$3": "$4"
#    "$5": "$6"
#
#- pattern: kafka.network<type=(.+), name=(.+), (.+)=(.+)><>([\d]?\w+)
#  name: kafka_network_$1_$2_$5
#  labels:
#    "$3": "$4"
#
#- pattern: kafka.server<type=(.+), name=(.+), (.+)=(.+)><>([\d]?\w+)
#  name: kafka_server_$1_$2_$5
#  labels:
#    "$3": "$4"
#
#- pattern: kafka.controller<type=(.+), name=(.+), (.+)=(.+)><>([\d]?\w+)
#  name: kafka_controller_$1_$2_$5
#  labels:
#    "$3": "$4"
#
